root: true
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2017
extends:
- eslint:recommended
- plugin:prettier/recommended
plugins:
- prettier
rules:
  no-inner-declarations: error
  no-unneeded-ternary: error
  no-useless-return: error
  no-var: error
